
server:
  port: 18787

spring:
  application:
    name: cat-gateway-web
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.profiles.active}
        file-extension: yml
        shared-configs:
          -${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        #extension-configs:


feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true